allowHostPorts: false
priority: 10
requiredDropCapabilities:
  - MKNOD
  - AUDIT_WRITE
  - KILL
  - NET_BIND_SERVICE
  - NET_RAW
  - FOWNER
  - FSETID
  - SYS_CHROOT
  - SETFCAP
  - SETPCAP
  - CHOWN
  - SETGID
  - SETUID
  - DAC_OVERRIDE
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsNonRoot
users: []
allowHostDirVolumePlugin: false
allowHostIPC: false
forbiddenSysctls:
  - '*'
seLinuxContext:
  type: RunAsAny
readOnlyRootFilesystem: false
fsGroup:
  ranges:
    - max: 4294967294
      min: 1
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
defaultAddCapabilities: []
supplementalGroups:
  ranges:
    - max: 4294967294
      min: 1
  type: MustRunAs
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - nfs
  - persistentVolumeClaim
  - projected
  - secret
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: false
apiVersion: security.openshift.io/v1
allowedCapabilities: null
defaultAllowPrivilegeEscalation: false
