kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: ibm-connect-direct-psp
spec:
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 4294967294
  seLinux:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  forbiddenSysctls:
    - '*'
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 4294967294
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 4294967294
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - nfs
    - persistentVolumeClaim
    - projected
    - secret
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - CHOWN
    - FOWNER
    - SETGID
    - SETUID
    - DAC_OVERRIDE
    - AUDIT_WRITE
    - SYS_CHROOT
